const FIELD_MAP: Record<string, string> = {
  ConnectionName: 'Name',
  Driver: 'Type',
  DatabaseHost: 'Host',
  DatabasePort: 'Port',
  DatabaseName: 'Database',
  DatabaseUser: 'Username',
  DatabasePassword: 'Password',
  Enviroment: 'Environment',
  StatusColor: 'Color Tag',
  GroupName: 'Group',
  SSHTunnelEnabled: 'SSH Tunnel',
  SSHHost: 'SSH Host',
  SSHPort: 'SSH Port',
  SSHUser: 'SSH Username',
  SSHPassword: 'SSH Password',
  SSHKeyPath: 'SSH Key Path',
  SSHPassphrase: 'SSH Key Passphrase',
  isOverSSH: 'Over SSH',
  useSSL: 'SSL Enabled',
  sslCACertPath: 'SSL CA Cert',
  sslClientCertPath: 'SSL Client Cert',
  sslKeyPath: 'SSL Key Path',
  DatabaseSocket: 'Socket Path',
  tLSMode: 'TLS Mode',
  ServerVersion: 'Server Version',
  ID: 'Connection ID',
  sslMode: 'SSL Mode',
  Port: 'Port',
  Host: 'Host',
  User: 'Username',
  Password: 'Password',
  Name: 'Name',
  Alias: 'Alias',
};

export function getFieldDisplayName(key: string): string {
  return FIELD_MAP[key] ?? key;
}
